// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image3":
            case "SpaceShip":return img`
. . . . . . . . . . . . . . . . 
. . . 2 5 f f . . . . . . . . . 
. . 2 4 f 1 1 f 2 . . . . . . . 
. . . 2 5 f f . . . . . . . . . 
. . . . . . f f f f f . . . . . 
. . . . . f f 1 1 1 1 f f . . . 
. . . . . f 1 1 1 1 8 9 1 f . . 
. . . . . f f 1 1 1 1 f f . . . 
. . . . . . f f f f f . . . . . 
. . . 2 5 f f . . . . . . . . . 
. . 2 4 f 1 1 f 2 . . . . . . . 
. . . 2 5 f f . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image5":
            case "LaserBeam":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 5 5 4 4 . . . . . . . . 
. . . 5 2 2 2 2 2 2 2 2 . . . . 
. . . . 5 5 4 4 . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image4":
            case "UFO":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . . . f 1 1 1 1 f . . . . . 
. . . f f f 1 1 1 1 f f f . . . 
. . f 2 2 2 2 2 2 2 2 2 2 f . . 
. . . f f f 2 2 2 2 f f f . . . 
. . . . . . f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "p9fyTX4#E92*kb(T36aD":
            case "Backround":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffff1fffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff1fffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff44444444444fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff44455555555555444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff44555555555555555555544fffffffffffff1fffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffff4555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff455555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffff45555555555555555555555555554fffffffffffffffffffffffff1fffffffffffffffffff1ffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff455555555555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff455555555555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffff455555555555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554ffffffffffff1ffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555555555554fffffffffffffffffffffffffffffff1fffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffff455555555555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff455555555555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff455555555555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffff4555555555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffff45555555555555555555555555554ffffffffffffff1fffffffffffffffffffffffffffffffffffff
fffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45555555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff455555555555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4555555555555555555555554ffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff44555555555555555555544fffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffff4555555555555555554fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff44455555555555444ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff44444444444fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccfffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffccc5555555aaaaaacccffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc5555555555aaaaaaaaaccffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc55555555555aaaaaaaaaaaacfffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc555555555555aaaaaaaaaaaaacffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc5555555555555aaaaaaaaaaaaaaccffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc55555555555555aaaaaaaaaaaaaaaaacfffffffffffffffffffffffffff
fffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc5555555555555aaaaaaaaaaaaaaaaaacfffffffffffff1fffffffffffff
ffffffffffffffffffff666666666ffff1ffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffc5555555555555aaaaaaaaaaaaaaaaaaaacffffffffffffffffffffffffff
fffffffffffffffffff68888888886ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc55555555555555aaaaaaaaaaaaaaaaaaaaacfffffffffffffffffffffffff
ffffffffffffffffff6998888888886ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc555555555555555aaaaaaaaaaaaaaaaaaaaa5cffffffffffffffffffffffff
fffffffffffffffff699998888888886fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc555555555555555aaaaaaaaaaaaaaaaaaaa55c1fffffffffffffffffffffff
ffffffffffffffff68899999888888886fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc5555555555555555aaaaaaaaaaaaaaaaaaa5555cfffffffffffffffffffffff
ffffffffffffffff68888999998888886fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffca555555555555555aaaaaaaaaaaaaaaaaa55555cfffffffffffffffffffffff
ffffffffffffffff66888889999999986fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffca5555555555555555aaaaaaaaaaaaaaa5555555cfffffffffffffffffffffff
ffffffffffffffff66688888889999996ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaa55555555555555aaaaaaaaaaaaaaaa55555555cffffffffffffffffffffff
ffffffffffffffff66666688888889996ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaa55555555555aaaaaaaaaaaaaaaaa55555555cffffffffffffffffffffff
ffffffffffffffff68666666888888886ffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffcaaaaaa555555555aaaaaaaaaaaaaaaaa555555555cffffffffffffffffffffff
ffffffffffffffff68888666668888886ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaa55555aaaaaaaaaaaaaaaaaaa5555555555cffffffffffffffffffffff
ffffffffffffffff68888886666666686f1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa555555555cffffffffffffffffffffff
ffffffffffffffff69988888866666666ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa555555555cffffffffffffffffffffff
fffffffffffffffff699888888888666fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa555555555cffffffffffffffffffffff
ffffffffffffffffff6998888888886ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa555555555cffffffffffffffffffffff
fffffffffffffffffff69999999996fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa55555555cffffffffffffffffffffff
ffffffffffffffffffff666666666fffffffffffffffffffffffffffffffffffffff1fffffffffffffffffff1ffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa5555555cffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa5555555cffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa5555555cffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa555555cffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa5555cfffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa5555cfffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa555cffffffffff1ffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaaaaaaa55aaaaaaaaaaaaaaaaaaaaaaaaacfffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcaaa5555555aaaaaaaaaaaaaaaaaaaaaaacffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffca55555555aaaaaaaaaaaaaaaaaaaaaacfffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffca555555555aaaaaaaaaaaaaaaaaaaaacfffffffffffffffffffffffffff
fffffffffff1ffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffcc555555555aaaaaaaa55aaaaaaaaccffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc5555555555555555555555aaacffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc55555555555555555555555cfffff1fffffffffffffffffffffffff
ffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcc5555555555555555555ccffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccc5555555555555cccffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccfffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffff1fffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff1ffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
